In [1]:
import httpx
import time
import pandas as pd
import re
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
import json
from pathlib import Path
import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

Skipping import of cpp extensions due to incompatible torch version 2.9.1 for torchao version 0.16.0             Please see https://github.com/pytorch/ao/issues/2919 for more info
W0728 13:36:37.268000 30234 torch/distributed/elastic/multiprocessing/redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.

In [20]:
language_classifier = pipeline(
    "text-classification",
    model = "papluca/xlm-roberta-base-language-detection"
)

def lang_result(text):
    results = language_classifier(
        text,
        truncation=True
    )
    return results[0]["label"]

model_name = "yangheng/deberta-v3-base-absa-v1.1"

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print("Using device:", device)

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
model.eval()


def aspect_sentiment(text, aspect, batch_size=16, max_length=512, stride=64):
    encoded = tokenizer(
        text,
        aspect,
        truncation=True,
        max_length=max_length,
        stride=stride,
        return_overflowing_tokens=True,
        padding=True,
        return_tensors="pt"
    )

    input_keys = ["input_ids", "attention_mask", "token_type_ids"]
    input_keys = [k for k in input_keys if k in encoded]

    all_probs = []

    with torch.inference_mode():
        n_chunks = encoded["input_ids"].shape[0]

        for start in range(0, n_chunks, batch_size):
            end = start + batch_size

            batch = {
                k: encoded[k][start:end].to(device)
                for k in input_keys
            }

            outputs = model(**batch)
            probs = F.softmax(outputs.logits, dim=-1)
            all_probs.append(probs)

    avg_probs = torch.cat(all_probs, dim=0).mean(dim=0).cpu()

    return {
        model.config.id2label[i]: float(avg_probs[i])
        for i in range(len(avg_probs))
    }

Device set to use mps:0

Using device: mps

/Users/mnatali/Projects/sentiment_analysis/.venv/lib/python3.13/site-packages/transformers/convert_slow_tokenizer.py:564: UserWarning: The sentencepiece tokenizer that you are converting to a fast tokenizer uses the byte fallback option which is not implemented in the fast tokenizers. In practice this means that the fast version of the tokenizer can produce unknown tokens whereas the sentencepiece version would have converted these unknown tokens into a sequence of byte tokens matching the original piece of text.
  warnings.warn(

In [21]:
print(aspect_sentiment("I love the weather here! However, datacenters are a concern. The friendly neighbors hake up for it though!", "datacenters"))
sentiment = aspect_sentiment("I love the weather here! However, datacenters are a concern. The friendly neighbors hake up for it though!", "datacenters")

post_sentiments = []
post_sentiment_degrees = []

post_sentiments.append(max(sentiment, key=sentiment.get))
post_sentiment_degrees.append(max(sentiment.values()))

print(post_sentiments[0], post_sentiment_degrees[0])

{'Negative': 0.9916238188743591, 'Neutral': 0.007077292539179325, 'Positive': 0.0012989335227757692}
Negative 0.9916238188743591

In [4]:
file_path = Path("/Users/mnatali/Projects/sentiment_analysis/brightdata_across_social_media_analysis/brightdata_social_exports/facebook_datacenters_posts.json")

with file_path.open("r", encoding="utf-8") as f:
    facebook_posts = json.load(f)

In [22]:
def remove_links(text):
    url_pattern = re.compile(r'\[https?://\S+\]|\(https?://\S+\)|\[www\.\S+\]|\(www\.\S+\)')
    cleaned_text = url_pattern.sub('', text)
    return cleaned_text

sample_string = "The board’s land use policy committee heard a presentation from the Department of Planning and Development about potential enhancements to data center use standards, including requiring a noise study and establishing a minimum distance from residential areas. The board had directed staff last May to provide research, findings and recommendations...  McKay said this process is designed to steer data centers into places that are most appropriate and make sure standards are set for environmental protections, noise mitigation and other issues that have people concerned. He said the county is learning from Loudoun and Prince William Counties, where data centers are becoming more and more prevalent...  [https://wjla.com/news/local/fairfax-county-considers-enhancing-data-center-guidelines-virginia-community-development-board-of-supervisors#](https://wjla.com/news/local/fairfax-county-considers-enhancing-data-center-guidelines-virginia-community-development-board-of-supervisors#)  A group of residents from the [Save Bren Mar From Data Center](https://sites.google.com/view/savebrenmar/home) group from the Mason District held up signs throughout Tuesday's legislative policy committee meeting, calling calling on the Fairfax county Supervisors to end by right data center development on commercial and industrial properties.  [https://patch.com/virginia/reston/data-center-zoning-policy-be-updated-fairfax-county-board](https://patch.com/virginia/reston/data-center-zoning-policy-be-updated-fairfax-county-board)Fairfax County considers enhancing data center guidelines"
result = remove_links(sample_string)
print(result)

english_post_ids = []
a = 0

for fb_post in facebook_posts:
    unclean_text = fb_post["content"]
    text = remove_links(unclean_text)
    language = lang_result(text)
    pid = fb_post["post_id"]
    if language == 'en':
        english_post_ids.append(pid)
    a += 1
    print("Posts scanned:", a, end="\r")

The board’s land use policy committee heard a presentation from the Department of Planning and Development about potential enhancements to data center use standards, including requiring a noise study and establishing a minimum distance from residential areas. The board had directed staff last May to provide research, findings and recommendations...  McKay said this process is designed to steer data centers into places that are most appropriate and make sure standards are set for environmental protections, noise mitigation and other issues that have people concerned. He said the county is learning from Loudoun and Prince William Counties, where data centers are becoming more and more prevalent...    A group of residents from the [Save Bren Mar From Data Center] group from the Mason District held up signs throughout Tuesday's legislative policy committee meeting, calling calling on the Fairfax county Supervisors to end by right data center development on commercial and industrial properties.  Fairfax County considers enhancing data center guidelines

KeyboardInterrupt:

In [23]:
print(len(english_post_ids))

25

In [24]:
post_sentiments = []
post_sentiment_degrees = []

a = 0
links = 0
for fb_post in facebook_posts:
    post_id = fb_post["post_id"]
    if post_id not in english_post_ids:
        continue
    a += 1
    clean_text = remove_links(fb_post["content"])
    if clean_text != fb_post["content"]:
        links += 1
    sentiment = aspect_sentiment(clean_text, "datacenters")
    post_sentiments.append(max(sentiment, key=sentiment.get))
    post_sentiment_degrees.append(max(sentiment.values()))
    print("Posts scanned:", a, end = "\r")

print("Posts scanned:", a)

Posts scanned: 25

In [25]:
sentiments_backup = post_sentiments.copy()
sentiment_degrees_backup = post_sentiment_degrees.copy()

data = {
    "sentiments": post_sentiments,
    "sentiment_degrees": post_sentiment_degrees
}

with open("facebook_sentiments_backup.json", "w") as f:
    json.dump(data, f)

In [26]:
posts = pd.DataFrame(columns=["ids", "text", "date", "likes", "number of comments", "number of shares", "page followers", "is page verified", "is paid partnership", "sentiment", "degree", "AWS", "Amazon", "Google", "Microsoft", "Azure", "Meta", "Oracle", "Equinix", "Digital Realty", "IBM", "Facebook", "Apple", "QTS", "Vantage", "CyrusOne", "CoreSite"])

post_ids = []
post_texts = []
post_dates = []
post_likes = []
post_comment_numbers = []
post_share_numbers = []
post_page_followers = []
post_is_page_verified = []
post_is_paid_partnership = []

a = 0

for fb_post in facebook_posts:
    post_id = fb_post["post_id"]
    if post_id not in english_post_ids:
        continue

    a += 1

    post_ids.append(fb_post["post_id"])
    post_texts.append(remove_links(fb_post["content"]))
    post_dates.append(fb_post["date_posted"])
    if fb_post["page_likes"] is None:
        post_likes.append(0)
    else:
        post_likes.append(fb_post["page_likes"])
    post_comment_numbers.append(fb_post["num_comments"])
    post_share_numbers.append(fb_post["num_shares"])
    if fb_post["page_followers"] is None:
        post_page_followers.append(0)
    else:
        post_page_followers.append(fb_post["page_followers"])
    post_is_page_verified.append(fb_post["page_is_verified"])
    post_is_paid_partnership.append(fb_post["is_sponsored"])


posts["ids"] = post_ids
posts["text"] = post_texts
posts["date"] = post_dates
posts["likes"] = post_likes
posts["number of comments"] = post_comment_numbers
posts["number of shares"] = post_share_numbers
posts["page followers"] = post_page_followers
posts["is page verified"] = post_is_page_verified
posts["is paid partnership"] = post_is_paid_partnership
posts["sentiment"] = post_sentiments
posts["degree"] = post_sentiment_degrees

print("Posts scanned:", a)

Posts scanned: 25

In [27]:
posts = posts.astype({
    "ids": "string",
    "text": "string",
    "date": "string",
    "likes": "int64",
    "number of comments": "int64",
    "number of shares": "int64",
    "page followers": "int64",
    "is page verified": "bool",
    "is paid partnership": "bool",
    "sentiment": "string",
    "degree": "float64",
    "AWS": "bool",
    "Amazon": "bool",
    "Google": "bool",
    "Microsoft": "bool",
    "Azure": "bool",
    "Meta": "bool",
    "Oracle": "bool",
    "Equinix": "bool",
    "Digital Realty": "bool",
    "IBM": "bool",
    "Facebook": "bool",
    "Apple": "bool",
    "QTS": "bool",
    "Vantage": "bool",
    "CyrusOne": "bool",
    "CoreSite": "bool"
})

In [32]:
company_terms = ["AWS","Amazon","Google","Microsoft","Azure","Meta","Oracle","Equinix","Digital Realty","IBM","Facebook","Apple","QTS","Vantage","CyrusOne","CoreSite"]

for c in company_terms:
    posts[c] = posts["text"].str.contains(rf'\b{re.escape(c)}\b', case=False, na=False)

posts_with_company = posts[posts[company_terms].any(axis=1)]
posts_with_company.head()

,ids,text,date,likes,number of comments,number of shares,page followers,is page verified,is paid partnership,sentiment,...,Oracle,Equinix,Digital Realty,IBM,Facebook,Apple,QTS,Vantage,CyrusOne,CoreSite
10,1145486004286829,Oracle to spend $40B on Nvidia chips for OpenA...,2025-05-29T11:15:07.000Z,0,0,0,130000,False,False,Neutral,...,True,False,False,False,False,False,False,False,False,False

In [33]:
len(posts)
posts.head()

,ids,text,date,likes,number of comments,number of shares,page followers,is page verified,is paid partnership,sentiment,...,Oracle,Equinix,Digital Realty,IBM,Facebook,Apple,QTS,Vantage,CyrusOne,CoreSite
0,1312080475614060,The Future of Data Centers 2019 is brought to ...,2019-05-29T13:45:44.000Z,9400,0,1,11000,False,False,Neutral,...,False,False,False,False,False,False,False,False,False,False
1,1097163855757616,🚀 GTC 2025: Redefining the Future Data Center ...,2025-03-11T14:00:08.000Z,5400,1,0,5900,False,False,Positive,...,False,False,False,False,False,False,False,False,False,False
2,1187839470053865,Back on the doors today! I had meaningful conv...,2025-07-08T23:26:04.000Z,0,0,0,5900,False,False,Negative,...,False,False,False,False,False,False,False,False,False,False
3,1215774918502343,You know to protect your data center from hack...,2016-10-01T07:44:16.000Z,4400,0,0,4500,False,False,Neutral,...,False,False,False,False,False,False,False,False,False,False
4,826143969520051,Don't miss this #Cisco Data Center Networking ...,2023-10-23T12:28:42.000Z,0,0,0,29,False,False,Neutral,...,False,False,False,False,False,False,False,False,False,False

In [34]:
print(posts.columns)

Index(['ids', 'text', 'date', 'likes', 'number of comments',
       'number of shares', 'page followers', 'is page verified',
       'is paid partnership', 'sentiment', 'degree', 'AWS', 'Amazon', 'Google',
       'Microsoft', 'Azure', 'Meta', 'Oracle', 'Equinix', 'Digital Realty',
       'IBM', 'Facebook', 'Apple', 'QTS', 'Vantage', 'CyrusOne', 'CoreSite'],
      dtype='object')

In [35]:
## total average sentiment calculation

pos = posts.loc[posts["sentiment"] == "Positive", "degree"].sum()
neg = posts.loc[posts["sentiment"] == "Negative", "degree"].sum()
total = posts["degree"].sum()
print("Average sentiment for all of facebook: ", (pos-neg)/total)

Average sentiment for all of facebook:  0.05143498513969831

In [36]:
pos = posts.loc[posts["sentiment"] == "Positive"]
neg = posts.loc[posts["sentiment"] == "Negative"]
neutral = posts.loc[posts["sentiment"] == "Neutral"]

print("Percent of posts that are neutral:", len(neutral)/len(posts))
print("Percent of posts that are negative:", len(neg)/len(posts))
print("Percent of posts that are positive:", len(pos)/len(posts))

really_pos = pos.loc[posts["degree"] > 0.70]
really_neg = neg.loc[posts["degree"] > 0.70]

if len(neg) != 0:
    print("Percent of negative posts that are really negative:", len(really_neg)/len(neg))
if len(pos) != 0:
    print("Percent of positive posts that are really positive:", len(really_pos)/len(pos))

Percent of posts that are neutral: 0.72
Percent of posts that are negative: 0.12
Percent of posts that are positive: 0.16
Percent of negative posts that are really negative: 0.3333333333333333
Percent of positive posts that are really positive: 0.75

In [37]:
def avg_sentiment_calculation(dataset):
    pos = dataset.loc[dataset["sentiment"] == "Positive", "degree"].sum()
    neg = dataset.loc[dataset["sentiment"] == "Negative", "degree"].sum()
    total = dataset["degree"].sum()
    if total != 0:
        return (pos-neg)/total
    else:
        return 0

posts['year'] = pd.to_datetime(posts['date']).dt.year

year_datasets = {year: posts[posts['year'] == year] for year in range(2010, 2027)}

for i in range(2010, 2027):
    print(f"Number of posts from {i}: ", len(year_datasets[i]))
    if(len(year_datasets[i]) != 0):
        print(f"Average sentiment for facebook posts from {i}: ", avg_sentiment_calculation(year_datasets[i]))

Number of posts from 2010:  0
Number of posts from 2011:  0
Number of posts from 2012:  0
Number of posts from 2013:  0
Number of posts from 2014:  0
Number of posts from 2015:  1
Average sentiment for facebook posts from 2015:  0.0
Number of posts from 2016:  3
Average sentiment for facebook posts from 2016:  0.0
Number of posts from 2017:  1
Average sentiment for facebook posts from 2017:  0.0
Number of posts from 2018:  0
Number of posts from 2019:  1
Average sentiment for facebook posts from 2019:  0.0
Number of posts from 2020:  4
Average sentiment for facebook posts from 2020:  -0.18059661956615708
Number of posts from 2021:  3
Average sentiment for facebook posts from 2021:  0.6636505374832127
Number of posts from 2022:  0
Number of posts from 2023:  3
Average sentiment for facebook posts from 2023:  -0.34172819200254395
Number of posts from 2024:  3
Average sentiment for facebook posts from 2024:  0.3811855808699243
Number of posts from 2025:  6
Average sentiment for facebook posts from 2025:  0.047064743120194166
Number of posts from 2026:  0

In [ ]:
categories = ["2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026"]
counts = [len(year_datasets[2011]), len(year_datasets[2012]), len(year_datasets[2013]), len(year_datasets[2014]), len(year_datasets[2015]), len(year_datasets[2016]), len(year_datasets[2017]), len(year_datasets[2018]), len(year_datasets[2019]), len(year_datasets[2020]), len(year_datasets[2021]), len(year_datasets[2022]), len(year_datasets[2023]), len(year_datasets[2024]), len(year_datasets[2025]), len(year_datasets[2025])]

plt.figure(figsize=(12, 6))
plt.bar(categories, counts)

plt.title(
    "Number of Posts over Time",
    fontsize=16,
    fontname="Arial"
)

plt.xlabel(
    "Year",
    fontsize=16,
    fontname="Arial"
)

plt.ylabel(
    "Number of posts",
    fontsize=16,
    fontname="Arial"
)
plt.show()

In [ ]:
categories = ["2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026"]
counts = [avg_sentiment_calculation(year_datasets[2011]), avg_sentiment_calculation(year_datasets[2012]), avg_sentiment_calculation(year_datasets[2013]), avg_sentiment_calculation(year_datasets[2014]), avg_sentiment_calculation(year_datasets[2015]), avg_sentiment_calculation(year_datasets[2016]), avg_sentiment_calculation(year_datasets[2017]), avg_sentiment_calculation(year_datasets[2018]), avg_sentiment_calculation(year_datasets[2019]), avg_sentiment_calculation(year_datasets[2020]), avg_sentiment_calculation(year_datasets[2021]), avg_sentiment_calculation(year_datasets[2022]), avg_sentiment_calculation(year_datasets[2023]), avg_sentiment_calculation(year_datasets[2024]), avg_sentiment_calculation(year_datasets[2025]), avg_sentiment_calculation(year_datasets[2025])]

plt.figure(figsize=(12, 6))
plt.bar(categories, counts)

plt.title(
    "Sentiment of Posts over Time",
    fontsize=16,
    fontname="Arial"
)

plt.xlabel(
    "Year",
    fontsize=16,
    fontname="Arial"
)

plt.ylabel(
    "Sentiment (-1 to 1)",
    fontsize=16,
    fontname="Arial"
)
plt.show()

In [50]:
def sentiment_by_company(company1, company2=None):
    company_posts = posts[
        (posts[company1] == True) | (posts[company2] == True) if company2 else (posts[company1] == True)
    ]
    return avg_sentiment_calculation(company_posts)

print("Number of Amazon-related posts:", len(posts[posts["AWS"] == True]) + len(posts[posts["Amazon"] == True]))
print("Average sentiment of AWS-related posts:", sentiment_by_company("AWS", "Amazon"))
print("Number of Google-related posts:", len(posts[posts["Google"] == True]))
print("Average sentiment of Google-related posts:", sentiment_by_company("Google"))
print("Number of Microsoft-related posts:", len(posts[posts["Microsoft"] == True]) + len(posts[posts["Azure"] == True]))
print("Average sentiment of Microsoft-related posts:", sentiment_by_company("Microsoft", "Azure"))
print("Number of Meta-related posts:", len(posts[posts["Meta"] == True]) + len(posts[posts["Facebook"] == True]))
print("Average sentiment of Meta-related posts:", sentiment_by_company("Meta"))
print("Number of Oracle-related posts:", len(posts[posts["Oracle"] == True]))
print("Average sentiment of Oracle-related posts:", sentiment_by_company("Oracle"))
print("Number of Equinix-related posts:", len(posts[posts["Equinix"] == True]))
print("Average sentiment of Equinix-related posts:", sentiment_by_company("Equinix"))
print("Number of Digital Realty-related posts:", len(posts[posts["Digital Realty"] == True]))
print("Average sentiment of Digital Realty-related posts:", sentiment_by_company("Digital Realty"))
print("Number of IBM-related posts:", len(posts[posts["IBM"] == True]))
print("Average sentiment of IBM-related posts:", sentiment_by_company("IBM"))
print("Number of Apple-related posts:", len(posts[posts["Apple"] == True]))
print("Average sentiment of Apple-related posts:", sentiment_by_company("Apple"))
print("Number of QTS-related posts:", len(posts[posts["QTS"] == True]))
print("Average sentiment of QTS-related posts:", sentiment_by_company("QTS"))
print("Number of Vantage-related posts:", len(posts[posts["Vantage"] == True]))
print("Average sentiment of Vantage-related posts:", sentiment_by_company("Vantage"))
print("Number of CyrusOne-related posts:", len(posts[posts["CyrusOne"] == True]))
print("Average sentiment of CyrusOne-related posts:", sentiment_by_company("CyrusOne"))
print("Number of CoreSite-related posts:", len(posts[posts["CoreSite"] == True]))
print("Average sentiment of CoreSite-related posts:", sentiment_by_company("CoreSite"))

Number of Amazon-related posts: 461
Average sentiment of AWS-related posts: 0.24011399848337064
Number of Google-related posts: 536
Average sentiment of Google-related posts: 0.26553759484462514
Number of Microsoft-related posts: 555
Average sentiment of Microsoft-related posts: 0.2876373119282363
Number of Meta-related posts: 467
Average sentiment of Meta-related posts: 0.31049756427976066
Number of Oracle-related posts: 265
Average sentiment of Oracle-related posts: 0.3070375019275063
Number of Equinix-related posts: 26
Average sentiment of Equinix-related posts: 0.29784196349797476
Number of Digital Realty-related posts: 14
Average sentiment of Digital Realty-related posts: 0.6208873550553056
Number of IBM-related posts: 37
Average sentiment of IBM-related posts: 0.395273989577136
Number of Apple-related posts: 120
Average sentiment of Apple-related posts: 0.229431729858914
Number of QTS-related posts: 10
Average sentiment of QTS-related posts: 0.07333690370588236
Number of Vantage-related posts: 18
Average sentiment of Vantage-related posts: 0.4691729051542612
Number of CyrusOne-related posts: 2
Average sentiment of CyrusOne-related posts: 0.38548875843228175
Number of CoreSite-related posts: 7
Average sentiment of CoreSite-related posts: 0.25117446167080837

In [46]:
def analysis_of_viral_posts(min):
    viral_posts = posts.loc[posts["likes"] >= min]
    print("What's considered viral: posts with over", min, "likes")
    print("Number of viral posts:", len(viral_posts))
    print("Average sentiment of viral posts:", avg_sentiment_calculation(viral_posts))
    print("Average sentiment of non-viral posts:", avg_sentiment_calculation(posts.loc[posts["likes"] < min]))
    print("Amount percent of viral posts that are polar (degree) > 0.70: ", len(viral_posts.loc[viral_posts["degree"] > 0.70])/len(viral_posts))

analysis_of_viral_posts(1000)
print("\n")
analysis_of_viral_posts(5000)
print("\n")
analysis_of_viral_posts(10000)

What's considered viral: posts with over 1000 likes
Number of viral posts: 7
Average sentiment of viral posts: 0.27040052536831233
Average sentiment of non-viral posts: -0.029843209704986322
Amount percent of viral posts that are polar (degree) > 0.70:  0.5714285714285714


What's considered viral: posts with over 5000 likes
Number of viral posts: 6
Average sentiment of viral posts: 0.30674411898561826
Average sentiment of non-viral posts: -0.02858601230121339
Amount percent of viral posts that are polar (degree) > 0.70:  0.6666666666666666


What's considered viral: posts with over 10000 likes
Number of viral posts: 4
Average sentiment of viral posts: 0.2166453366948588
Average sentiment of non-viral posts: 0.02188544579408794
Amount percent of viral posts that are polar (degree) > 0.70:  0.5