In [74]:
import httpx
import time
import pandas as pd
import re
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline
import json
from pathlib import Path
import numpy as np
from tqdm.auto import tqdm
import torch
import torch.nn.functional as F

In [75]:
language_classifier = pipeline(
    "text-classification",
    model = "papluca/xlm-roberta-base-language-detection"
)

def lang_result(text):
    results = language_classifier(
        text,
        truncation=True
    )
    return results[0]["label"]

theme_classifier = pipeline(
    "zero-shot-classification",
    model="MoritzLaurer/deberta-v3-base-zeroshot-v2.0",
    multi_label = True
)

def theme_result(text, theme_labels):
    return theme_classifier(
        text,
        candidate_labels=theme_labels,
        hypothesis_template="This post discusses {}.",
        multi_label=True
    )

model_name = "yangheng/deberta-v3-base-absa-v1.1"

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")
print("Using device:", device)

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to(device)
model.eval()


def aspect_sentiment(text, aspect, batch_size=16, max_length=512, stride=64):
    encoded = tokenizer(
        text,
        aspect,
        truncation=True,
        max_length=max_length,
        stride=stride,
        return_overflowing_tokens=True,
        padding=True,
        return_tensors="pt"
    )

    input_keys = ["input_ids", "attention_mask", "token_type_ids"]
    input_keys = [k for k in input_keys if k in encoded]

    all_probs = []

    with torch.inference_mode():
        n_chunks = encoded["input_ids"].shape[0]

        for start in range(0, n_chunks, batch_size):
            end = start + batch_size

            batch = {
                k: encoded[k][start:end].to(device)
                for k in input_keys
            }

            outputs = model(**batch)
            probs = F.softmax(outputs.logits, dim=-1)
            all_probs.append(probs)

    avg_probs = torch.cat(all_probs, dim=0).mean(dim=0).cpu()

    return {
        model.config.id2label[i]: float(avg_probs[i])
        for i in range(len(avg_probs))
    }

Device set to use mps:0
Device set to use mps:0

Using device: mps

In [76]:
file_path_1 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/1st_4_subreddits_description.json")
file_path_2 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/1st_4_subreddits_title.json")
file_path_3 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/2nd_4_subreddits_description.json")
file_path_4 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/2nd_4_subreddits_title.json")
file_path_5 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/3rd_4_subreddits_description.json")
file_path_6 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/3rd_4_subreddits_title.json")
file_path_7 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/4th_4_subreddits_description.json")
file_path_8 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/4th_4_subreddits_title.json")
file_path_9 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/5th_3_subreddits_description.json")
file_path_10 = Path("/Users/mnatali/Projects/sentiment_analysis/reddit_across_subreddits_analysis/brightdata_subreddit_exports/5th_3_subreddits_title.json")


with file_path_1.open("r", encoding="utf-8") as f:
    posts_1 = json.load(f)
with file_path_2.open("r", encoding="utf-8") as f:
    posts_2 = json.load(f)
with file_path_3.open("r", encoding="utf-8") as f:
    posts_3 = json.load(f)
with file_path_4.open("r", encoding="utf-8") as f:
    posts_4 = json.load(f)
with file_path_5.open("r", encoding="utf-8") as f:  
    posts_5 = json.load(f)
with file_path_6.open("r", encoding="utf-8") as f:
    posts_6 = json.load(f)
with file_path_7.open("r", encoding="utf-8") as f:
    posts_7 = json.load(f)
with file_path_8.open("r", encoding="utf-8") as f:
    posts_8 = json.load(f)
with file_path_9.open("r", encoding="utf-8") as f:
    posts_9 = json.load(f)
with file_path_10.open("r", encoding="utf-8") as f:
    posts_10 = json.load(f)


post_lists = [posts_1, posts_2, posts_3, posts_4, posts_5, posts_6, posts_7, posts_8, posts_9, posts_10]
subreddit_posts = []
seen_post_ids = set()

for post_list in post_lists:
    for post in post_list:
        post_id = post.get("post_id")
        if post_id in seen_post_ids:
            continue
        seen_post_ids.add(post_id)
        subreddit_posts.append(post)

In [77]:
def remove_links(text):
    url_pattern = re.compile(r'[\[(]?(?:https?://|www\.)\S+[\])]?' )
    return url_pattern.sub('', text)

print(remove_links("Data center was approved in leesburg https://www.loudounnow.com/news/supervisors-narrowly-approve-data-center-near-leesburg/article_3e355c29-4dbc-42df-bdb9-37d86f3013ad.html Honestly I am just super upset. Seemed to me a majority of the community does not want another data center, but yet 5 of the board still voted in favor of it."))

Data center was approved in leesburg  Honestly I am just super upset. Seemed to me a majority of the community does not want another data center, but yet 5 of the board still voted in favor of it.

In [78]:
english_post_ids = []
a = 0

for sub_post in subreddit_posts:
    unclean_text = sub_post["title"] + " " + sub_post["description"] if sub_post["description"] else sub_post["title"]
    text = remove_links(unclean_text)
    language = lang_result(text)
    pid = sub_post["post_id"]
    if language == 'en':
        english_post_ids.append(pid)
    a += 1
    print("Posts scanned:", a, end="\r")

print(len(english_post_ids))

604ts scanned: 613

In [79]:
all_post_ids = []

env_post_ids = []
env_post_sentiments = []
env_post_sentiment_degrees = []

infr_post_ids = []
infr_post_sentiments = []
infr_post_sentiment_degrees = []

housing_post_ids = []
housing_post_sentiments = []
housing_post_sentiment_degrees = []

econ_post_ids = []
econ_post_sentiments = []
econ_post_sentiment_degrees = []

life_qual_post_ids = []
life_qual_post_sentiments = []
life_qual_post_sentiment_degrees = []

aesth_post_ids = []
aesth_post_sentiments = []
aesth_post_sentiment_degrees = []

gov_post_ids = []
gov_post_sentiments = []
gov_post_sentiment_degrees = []

tech_post_ids = []
tech_post_sentiments = []
tech_post_sentiment_degrees = []

not_useful_post_ids = []

themes = ["visual impact of datacenters", "data centers infrastructure and impact on home utilities", "impact of data centers on housing costs and property values", "impact of data centers on the economy and job market", "quality of life around data centers, noise, and light pollution", "environmental impact of data centers", "government decisions and policies relating to data centers", "technology performance and growth"]

matched_posts = 0
more_than_one_theme_posts = 0

a = 0

for post in subreddit_posts:
    post_id = post["post_id"]
    if post_id not in english_post_ids:
        continue

    a += 1

    post_id = post["post_id"]
    all_post_ids.append(post_id)
    unclean_text = post["title"] + post["description"] if post["description"] else post["title"]
    text = remove_links(unclean_text)

    final_labels = []

    theme_scores = theme_result(
        text,
        themes
    )
    
    for i in range(len(theme_scores['labels'])):
        if theme_scores['scores'][i] > 0.5:
            final_labels.append(theme_scores['labels'][i])
    
    if len(final_labels) > 0:
        matched_posts += 1
    else:
        not_useful_post_ids.append(post_id)
    
    if len(final_labels) > 1:
        more_than_one_theme_posts += 1
    

    for label in final_labels:
        total_sentiment = aspect_sentiment(text, label)
        post_sentiment = max(total_sentiment, key=total_sentiment.get)
        post_degree = max(total_sentiment.values())

        if label == "visual impact of datacenters":
            aesth_post_ids.append(post_id)
            aesth_post_sentiments.append(post_sentiment)
            aesth_post_sentiment_degrees.append(post_degree)
        if label == "data centers infrastructure and impact on home utilities":
            infr_post_ids.append(post_id)
            infr_post_sentiments.append(post_sentiment)
            infr_post_sentiment_degrees.append(post_degree)
        if label == "impact of data centers on housing costs and property values":
            housing_post_ids.append(post_id)
            housing_post_sentiments.append(post_sentiment)
            housing_post_sentiment_degrees.append(post_degree)
        if label == "impact of data centers on the economy and job market":
            econ_post_ids.append(post_id)
            econ_post_sentiments.append(post_sentiment)
            econ_post_sentiment_degrees.append(post_degree)
        if label == "quality of life around data centers, noise, and light pollution":
            life_qual_post_ids.append(post_id)
            life_qual_post_sentiments.append(post_sentiment)
            life_qual_post_sentiment_degrees.append(post_degree)
        if label == "environmental impact of data centers":
            env_post_ids.append(post_id)
            env_post_sentiments.append(post_sentiment)
            env_post_sentiment_degrees.append(post_degree)
        if label == "government decisions and policies relating to data centers":
            gov_post_ids.append(post_id)
            gov_post_sentiments.append(post_sentiment)
            gov_post_sentiment_degrees.append(post_degree)
        if label == "technology performance and growth":
            tech_post_ids.append(post_id)
            tech_post_sentiments.append(post_sentiment)
            tech_post_sentiment_degrees.append(post_degree)

        print("Posts scanned:", a, end="\r")

print("Total posts scanned:", len(all_post_ids))
print("Total posts with a theme:", matched_posts)
print("Found environmental posts:", len(env_post_ids))
print("Found infrastructure posts:", len(infr_post_ids))
print("Found housing posts:", len(housing_post_ids))
print("Found economic posts:", len(econ_post_ids))
print("Found life quality posts:", len(life_qual_post_ids))
print("Found aesthetic posts:", len(aesth_post_ids))
print("Found government posts:", len(gov_post_ids))
print("Found technological posts:", len(tech_post_ids))

KeyboardInterrupt:

In [ ]:
theme_lists = [env_post_ids, infr_post_ids, housing_post_ids, econ_post_ids, life_qual_post_ids, aesth_post_ids, gov_post_ids, tech_post_ids]
posts = pd.DataFrame(columns=["ids", "text", "date", "upvotes", "number of comments", "subreddit", "environment", "infrastructure", "housing", "economy", "life quality", "aesthetics", "government", "technology", "AWS", "Amazon", "Google", "Microsoft", "Azure", "Meta", "Oracle", "Equinix", "Digital Realty", "IBM", "Facebook", "Apple", "QTS", "Vantage", "CyrusOne", "CoreSite"])
datacenters_keywords = ["datacenter", "data center", "datacentre", "data centre"]

for theme in theme_lists:
    df1 = pd.DataFrame(columns=["ids", "text", "date", "upvotes", "number of comments", "subreddit", "environment", "infrastructure", "housing", "economy", "life quality", "aesthetics", "government", "technology", "AWS", "Amazon", "Google", "Microsoft", "Azure", "Meta", "Oracle", "Equinix", "Digital Realty", "IBM", "Facebook", "Apple", "QTS", "Vantage", "CyrusOne", "CoreSite"])
    post_ids = []
    post_texts = []
    post_dates = []
    post_num_comments = []
    post_upvotes = []
    post_subreddits = []

    for post in subreddit_posts:
        if post["post_id"] in theme:
            post_ids.append(post["post_id"])
            unclean_text = post["title"] + " " + post["description"] if post["description"] else post["title"]
            text = remove_links(unclean_text)
            post_texts.append(text)
            post_dates.append(post["date_posted"])
            post_num_comments.append(post["num_comments"])
            post_upvotes.append(post["num_upvotes"])
            post_subreddits.append(post["community_name"])


    df1["ids"] = post_ids
    df1["text"] = post_texts
    df1["date"] = post_dates
    df1["number of comments"] = post_num_comments
    df1["upvotes"] = post_upvotes
    df1["subreddit"] = post_subreddits

    
    for col in ["environment", "infrastructure", "housing", "economy", "life quality", "aesthetics", "government", "technology"]:
        df1[col] = False

    for col in ["environment sentiment", "environment sentiment degree", "infrastructure sentiment", "infrastructure sentiment degree", "housing sentiment", "housing sentiment degree", "economy sentiment", "economy sentiment degree", "life quality sentiment", "life quality sentiment degree", "aesthetics sentiment", "aesthetics sentiment degree", "government sentiment", "government sentiment degree", "technology sentiment", "technology sentiment degree"]:
        df1[col] = None

    if theme == env_post_ids:
        df1["environment"] = True
        df1["environment sentiment"] = env_post_sentiments
        df1["environment sentiment degree"] = env_post_sentiment_degrees
    if theme == infr_post_ids:
        df1["infrastructure"] = True
        df1["infrastructure sentiment"] = infr_post_sentiments
        df1["infrastructure sentiment degree"] = infr_post_sentiment_degrees
    if theme == housing_post_ids:
        df1["housing"] = True
        df1["housing sentiment"] = housing_post_sentiments
        df1["housing sentiment degree"] = housing_post_sentiment_degrees
    if theme == econ_post_ids:
        df1["economy"] = True
        df1["economy sentiment"] = econ_post_sentiments
        df1["economy sentiment degree"] = econ_post_sentiment_degrees
    if theme == life_qual_post_ids:
        df1["life quality"] = True
        df1["life quality sentiment"] = life_qual_post_sentiments
        df1["life quality sentiment degree"] = life_qual_post_sentiment_degrees
    if theme == aesth_post_ids:
        df1["aesthetics"] = True
        df1["aesthetics sentiment"] = aesth_post_sentiments
        df1["aesthetics sentiment degree"] = aesth_post_sentiment_degrees
    if theme == gov_post_ids:
        df1["government"] = True
        df1["government sentiment"] = gov_post_sentiments
        df1["government sentiment degree"] = gov_post_sentiment_degrees
    if theme == tech_post_ids:
        df1["technology"] = True
        df1["technology sentiment"] = tech_post_sentiments
        df1["technology sentiment degree"] = tech_post_sentiment_degrees
    posts = pd.concat([posts, df1], ignore_index=True)

/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)
/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)
/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)
/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)
/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)
/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)
/var/folders/9m/h28gbbc970j03ncf7v7dhqk80000gq/T/ipykernel_20572/1328382018.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  posts = pd.concat([posts, df1], ignore_index=True)

In [ ]:
len(posts)

627

In [ ]:
grouping_cols = ["ids", "text", "date"]

theme_cols = ["environment", "infrastructure", "housing", "economy", "life quality", "aesthetics", "government", "technology"]
sent_cols  = ["environment sentiment", "environment sentiment degree", "infrastructure sentiment", "infrastructure sentiment degree", "housing sentiment", "housing sentiment degree", "economy sentiment", "economy sentiment degree", "life quality sentiment", "life quality sentiment degree", "aesthetics sentiment", "aesthetics sentiment degree", "government sentiment", "government sentiment degree", "technology sentiment", "technology sentiment degree"]

def first_non_null(s):
    s = s.dropna()
    return s.iloc[0] if len(s) else np.nan

agg = {c: "max" for c in theme_cols}              # True if any True
agg.update({c: first_non_null for c in sent_cols}) # keep the real sentiment if present

posts = posts.groupby(grouping_cols, as_index=False).agg(agg)
print(len(posts))
posts.head()

451

,ids,text,date,environment,infrastructure,housing,economy,life quality,aesthetics,government,...,economy sentiment,economy sentiment degree,life quality sentiment,life quality sentiment degree,aesthetics sentiment,aesthetics sentiment degree,government sentiment,government sentiment degree,technology sentiment,technology sentiment degree
0,t3_185gmqm,Virginia's 'Data Center Alley' residents say a...,2023-11-27T23:02:54.851Z,False,False,False,False,True,False,False,...,NaN,NaN,Negative,0.983447,NaN,NaN,NaN,NaN,Neutral,0.486409
1,t3_1942s4p,Top 50 Data Center Markets by Power Consumption,2024-01-11T14:19:37.275Z,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Positive,0.941554
2,t3_1dfawda,"Unfortunately I don’t live there anymore, but ...",2024-06-13T21:57:35.912Z,False,False,True,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,t3_1febz9m,Fairfax County board approves new data center ...,2024-09-11T14:48:08.328Z,False,False,False,False,False,False,True,...,NaN,NaN,NaN,NaN,NaN,NaN,Neutral,0.911327,NaN,NaN
4,t3_1fiznzw,Our digital lives need massive data centers. W...,2024-09-17T13:45:35.462Z,False,False,False,False,False,False,False,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Neutral,0.705571

In [ ]:
print(posts.columns)

Index(['ids', 'text', 'date', 'environment', 'infrastructure', 'housing',
       'economy', 'life quality', 'aesthetics', 'government', 'technology',
       'environment sentiment', 'environment sentiment degree',
       'infrastructure sentiment', 'infrastructure sentiment degree',
       'housing sentiment', 'housing sentiment degree', 'economy sentiment',
       'economy sentiment degree', 'life quality sentiment',
       'life quality sentiment degree', 'aesthetics sentiment',
       'aesthetics sentiment degree', 'government sentiment',
       'government sentiment degree', 'technology sentiment',
       'technology sentiment degree'],
      dtype='object')

In [ ]:
posts.to_json('subreddits_ABSA_entire_dataframe.json', orient='records', indent=4)

In [ ]:
posts_by_id = {post["post_id"]: post for post in subreddit_posts}
gov_links = []

for id in gov_post_ids:
    post = posts_by_id.get(id)
    gov_links.append(post["url"])

print(gov_links)

['https://www.reddit.com/r/Virginia/comments/1tiqg8b/va_gave_data_centers_a_154myear_tax_break_in_2008/', 'https://www.reddit.com/r/Virginia/comments/1skjvnk/iso_data_center_impacts_long_term_jobs_promises/', 'https://www.reddit.com/r/Virginia/comments/1u26kfu/gov_spanberger_is_wrong_on_data_center_tax_breaks/', 'https://www.reddit.com/r/Virginia/comments/1k7ss6k/what_youngkin_did_for_us_in_his_last_year_and/', 'https://www.reddit.com/r/Virginia/comments/1u2c7gb/virginias_business_reputation_at_the_center_of/', 'https://www.reddit.com/r/Virginia/comments/1sgzr3f/gov_spanberger_addresses_ice_misinformation_and/', 'https://www.reddit.com/r/Virginia/comments/1siifyp/the_virginia_data_center_tax_exemption_call_your/', 'https://www.reddit.com/r/nova/comments/1sw9eoq/wanted_to_understand_why_my_dominion_bill_was/', 'https://www.reddit.com/r/Virginia/comments/1sm7vyd/virginia_lawmakers_clash_over_16b_data_center_tax/', 'https://www.reddit.com/r/nova/comments/1u26dts/gov_spanberger_is_wrong_on_data_center_tax_breaks/', 'https://www.reddit.com/r/arizona/comments/1ow2lf2/the_proposed_data_centers_in_page_and_marana/', 'https://reddit.com/r/nova/comments/1m1veop/data_center_was_approved_in_leesburg', 'https://www.reddit.com/r/Virginia/comments/1sr9a26/tomorrow_is_election_day_should_i_vote_yes_or_no/', 'https://www.reddit.com/r/Virginia/comments/1u4w1u8/support_ending_virginias_data_center_tax_giveaway/', 'https://www.reddit.com/r/nova/comments/1sgcmee/no_matter_how_you_feel_about_data_centers_its/', 'https://www.reddit.com/r/Virginia/comments/1tipxj3/virginia_tribes_say_data_centers_could_harm_rivers/', 'https://www.reddit.com/r/nova/comments/1tqf8p1/spanberger_campaigned_on_fairness_now_its_time_to/', 'https://www.reddit.com/r/Virginia/comments/1ti67gs/the_virginia_primaries_before_for_this_years/', 'https://www.reddit.com/r/Virginia/comments/1u45ibm/virginia_house_drops_74b_budget_draft_ahead_of/', 'https://www.reddit.com/r/Virginia/comments/1sukevg/virginia_money_committee_heads_point_the_finger/', 'https://www.reddit.com/r/nova/comments/1tuc5xq/spanberger_reports_that_suddenly_theres_an_extra/', 'https://reddit.com/r/Virginia/comments/1rn9vi6/halifax_county_eyeing_data_centers_as_potential', 'https://www.reddit.com/r/nova/comments/1u4bk5b/tell_me_how_its_ok_for_a_drop_of_our_drinking/', 'https://www.reddit.com/r/nova/comments/1t1pxn9/virginias_data_center_tax_break_is_costing_the/', 'https://www.reddit.com/r/nova/comments/1tk20a2/datacenter_showdown_in_va_legislature_could_lead/', 'https://www.reddit.com/r/Virginia/comments/1rr1nct/virginias_starting_to_question_whether_its_giant/', 'https://www.reddit.com/r/nova/comments/1sej8n4/i_took_decibel_readings_of_the_vantage_data/', 'https://www.reddit.com/r/nova/comments/1mzrm4e/suggested_toll_relief_and_dulles_access_road/', 'https://www.reddit.com/r/Virginia/comments/1sd5af2/google_struck_a_secret_deal_for_3_data_centers_in/', 'https://www.reddit.com/r/Virginia/comments/1n8diha/virginias_data_center_boom_tests_clean_energy_law/', 'https://www.reddit.com/r/Virginia/comments/1t85aj4/commentary_spanbergers_data_center_position_is/', 'https://www.reddit.com/r/Virginia/comments/1sx5mzl/west_virginias_governor_courts_data_center/', 'https://www.reddit.com/r/Virginia/comments/1sv0yto/data_center_tax_exemption_changes_still_holding/', 'https://reddit.com/r/nova/comments/1pbbwru/our_regulators_are_trying_to_make_it_easier_for', 'https://www.reddit.com/r/nova/comments/1sdo3xz/data_center_onsite_gas_turbines_health_hazard/', 'https://www.reddit.com/r/Virginia/comments/1u1e97w/press_release_virginia_is_no_longer_deciding/', 'https://www.reddit.com/r/nova/comments/1sfujau/va_court_of_appeals_stops_major_data_center/', 'https://www.reddit.com/r/Virginia/comments/1stq7kc/no_state_budget_expected_until_june_speaker_says/', 'https://www.reddit.com/r/Virginia/comments/1sm91r1/megasite_project_could_be_in_jeopardy_if_data/', 'https://www.reddit.com/r/nova/comments/1ry0ilm/fairfax_county_oks_chantilly_land_sale_to_data/', 'https://www.reddit.com/r/Virginia/comments/1sump5z/local_governments_in_virginia_race_to_attract/', 'https://www.reddit.com/r/nova/comments/1ta1rr2/whats_next_for_the_digital_gateway_data_center/', 'https://www.reddit.com/r/Virginia/comments/1s49w37/sen_warner_calls_ai_data_center_moratorium/', 'https://www.reddit.com/r/Virginia/comments/1nw1az0/virginia_could_show_how_to_manage_data_center/', 'https://www.reddit.com/r/nova/comments/1sewrrs/as_data_center_noise_concerns_grow_loudoun_co/', 'https://www.reddit.com/r/nova/comments/1rwa7ut/loudoun_county_will_fight_to_keep_amazon_data/', 'https://www.reddit.com/r/Virginia/comments/1stq93q/data_center_moratorium_a_fault_line_in_dem/', 'https://www.reddit.com/r/Virginia/comments/1u3xdwp/new_virginia_law_requires_data_center_water_usage/', 'https://www.reddit.com/r/Virginia/comments/1suono8/commentary_the_governors_amendments_to_energy_and/', 'https://www.reddit.com/r/nova/comments/1s49wtj/sen_warner_calls_ai_data_center_moratorium/', 'https://www.reddit.com/r/arizona/comments/1plta23/this_is_the_land_the_city_of_page_is_selling_to/', 'https://www.reddit.com/r/Virginia/comments/1mia19o/va_delegate_proposes_child_opportunity_accounts/', 'https://www.reddit.com/r/Virginia/comments/1txme7r/speaker_scott_says_virginia_should_honor_its_word/', 'https://www.reddit.com/r/Virginia/comments/1talgc6/trumps_epa_seeks_looser_construction_rules_for/', 'https://www.reddit.com/r/Virginia/comments/1m2pahj/virginia_is_for_data_centers_residents_are/', 'https://www.reddit.com/r/Virginia/comments/1szxjeb/new_state_law_mandates_review_of_dominions_load/', 'https://www.reddit.com/r/Virginia/comments/1tq23em/opinion_spanberger_on_data_centers_im_not_going/', 'https://www.reddit.com/r/Virginia/comments/1toahd4/virginia_faces_june_deadline_to_approve_budget_as/', 'https://reddit.com/r/nova/comments/1febz9m/fairfax_county_board_approves_new_data_center', 'https://reddit.com/r/Virginia/comments/1h8szf0/data_centers_approved_solar_farms_rejected_what', 'https://www.reddit.com/r/Virginia/comments/1sfujfh/va_court_of_appeals_stops_major_data_center/', 'https://www.reddit.com/r/Virginia/comments/1tkj1rb/opinion_cabinet_secretary_southside_county_loses/', 'https://www.reddit.com/r/Virginia/comments/1t221fw/virginias_data_center_tax_break_is_costing_the/', 'https://www.reddit.com/r/Virginia/comments/1oqts0s/with_democrats_in_charge_spanberger_targets_lower/', 'https://www.reddit.com/r/Virginia/comments/1thwqm7/union_members_confront_virginia_senators_as/', 'https://www.reddit.com/r/Virginia/comments/1twpj0m/this_shouldve_happened_last_year_king_george/', 'https://www.reddit.com/r/arizona/comments/1tr3kye/largest_proposed_data_center_in_arizona_to_be/', 'https://www.reddit.com/r/Virginia/comments/1szxlbj/heres_what_house_lawmakers_want_to_require_of/', 'https://www.reddit.com/r/nova/comments/1seuk2s/as_data_center_noise_concerns_grow_loudoun_co/', 'https://www.reddit.com/r/Virginia/comments/1tkw53s/virginia_beach_approved_800k_to_expand_a_local/', 'https://www.reddit.com/r/Virginia/comments/1so0aax/governor_amends_bills_that_shift_costs_onto_data/', 'https://www.reddit.com/r/Virginia/comments/1tv7cef/virginia_beach_mayor_ban_largescale_data_centers/', 'https://www.reddit.com/r/Virginia/comments/1sumk5s/virginia_lawmakers_recess_special_session_without/', 'https://www.reddit.com/r/texas/comments/1siorvx/lawmakers_probe_regulators_and_industry_leaders/', 'https://www.reddit.com/r/Austin/comments/1th3agz/minority_report_taylor_data_center_plan_raises/', 'https://www.reddit.com/r/texas/comments/1tnltf9/guadalupe_county_voted_in_favor_of_a_500_million/', 'https://www.reddit.com/r/ChandlerAZ/comments/1ojcms6/city_council_meeting_nov_10th/', 'https://www.reddit.com/r/texas/comments/1qizegn/will_texas_control_the_datacenter_boom_or_will_it/', 'https://www.reddit.com/r/texas/comments/1tlzwr6/guadalupe_county_voted_in_favor_of_a_500_million/', 'https://www.reddit.com/r/ChandlerAZ/comments/1pkk14x/chandler_city_council_denies_new_ai_data_center/', 'https://www.reddit.com/r/texas/comments/1u24kf3/why_texas_should_hit_pause_on_ai_data_centers/', 'https://www.reddit.com/r/texas/comments/1tv9ws5/sid_miller_to_join_democratic_nominee_for/', 'https://www.reddit.com/r/texas/comments/1sfop9e/texas_is_giving_data_centers_more_than_1_billion/', 'https://www.reddit.com/r/texas/comments/1sk7aoy/granbury_residents_sue_city_over_data_center_plan/', 'https://www.reddit.com/r/texas/comments/1t21009/proposed_fort_bliss_data_center_could_use_more/', 'https://www.reddit.com/r/texas/comments/1shpr8g/texas_is_giving_data_centers_more_than_1_billion/', 'https://www.reddit.com/r/texas/comments/1sfstpc/texas_is_giving_data_centers_more_than_1_billion/', 'https://www.reddit.com/r/texas/comments/1t6b94p/texas_republicans_have_a_data_center_problem/', 'https://www.reddit.com/r/texas/comments/1u19fg6/data_center_boom_exposes_gop_faultlines_over/', 'https://www.reddit.com/r/texas/comments/1r410af/texans_are_demanding_their_local_governments_push/', 'https://www.reddit.com/r/texas/comments/1u08mda/a_farmer_donated_land_to_turn_into_a_park_the/', 'https://www.reddit.com/r/texas/comments/1txuqhv/texas_county_rescinds_its_data_center_moratorium/', 'https://www.reddit.com/r/Dallas/comments/1ta8u7l/new_wilmer_council_member_aims_to_take_on_rapid/', 'https://www.reddit.com/r/texas/comments/1nqytvq/texas_planners_dont_know_how_much_water_data/', 'https://www.reddit.com/r/texas/comments/1tvzfwx/ercot_votes_to_streamline_process_for_data/', 'https://www.reddit.com/r/Austin/comments/1sou7e3/hutto_data_center_rezoning_request_withdrawn_by/', 'https://www.reddit.com/r/texas/comments/1u250oy/abbott_recommends_sweeping_data_center_regulation/', 'https://www.reddit.com/r/texas/comments/1s4xtu5/demand_transparency_in_rio_grande_valley_data/', 'https://www.reddit.com/r/Portland/comments/1rk5blz/understanding_upcoming_gov_primary/', 'https://www.reddit.com/r/Seattle/comments/1u1hyh6/city_council_packed_with_public_commenters_signed/', 'https://www.reddit.com/r/Washington/comments/1r89wnp/strong_data_center_regulation_is_imperative/', 'https://www.reddit.com/r/Seattle/comments/1u1lo4r/city_council_passes_emergency_data_center/', 'https://www.reddit.com/r/Washington/comments/1s9tz6d/washington_to_end_data_center_tax_break_for/', 'https://www.reddit.com/r/Portland/comments/1u1rbks/oregon_regulators_delay_massive_data_center_rate/', 'https://www.reddit.com/r/Seattle/comments/1u1mta5/seattle_passes_data_center_moratorium/', 'https://www.reddit.com/r/oregon/comments/1t5m53v/as_moratorium_approaches_hillsboro_lock_in_tax/', 'https://www.reddit.com/r/oregon/comments/1ts8azc/boomtown_and_battleground_small_oregon_county/', 'https://www.reddit.com/r/Seattle/comments/1sslpq0/seattle_to_explore_moratorium_on_data_centers/', 'https://www.reddit.com/r/Washington/comments/1rk55y8/its_lights_out_for_wa_legislatures_effort_to/', 'https://www.reddit.com/r/oregon/comments/1sclre9/how_do_we_stop_ai_data_center_expansion_in_oregon/', 'https://www.reddit.com/r/Seattle/comments/1t0g5ec/councilmembers_introducing_moratorium_on_data/', 'https://www.reddit.com/r/oregon/comments/1t8gci0/oregon_regulators_move_to_make_data_centers_pay/', 'https://www.reddit.com/r/Portland/comments/1t5w1mo/hillsboro_is_promising_data_center_tax_breaks/', 'https://www.reddit.com/r/Seattle/comments/1u0lzzy/tomorrow_6926_2pm_join_us_at_city_hall_for_the/', 'https://www.reddit.com/r/Seattle/comments/1tw9rk0/seattles_data_center_moratorium_moves_forward/', 'https://www.reddit.com/r/oregon/comments/1ttsz8y/hillsboro_considers_pause_on_new_data_centers/', 'https://www.reddit.com/r/Ohio/comments/1sb2mas/ai_datacenter_ban_petition/', 'https://www.reddit.com/r/Ohio/comments/1tz85v7/ohio_lawmakers_are_fasttracking_data_center/', 'https://www.reddit.com/r/SeattleWA/comments/1tolz7h/seattle_advances_data_center_moratorium_amid/', 'https://www.reddit.com/r/SeattleWA/comments/1u1i1fv/city_council_packed_with_public_commenters_signed/', 'https://reddit.com/r/Ohio/comments/1r0gwhd/data_center_accountability', 'https://www.reddit.com/r/Ohio/comments/1tkkayb/ohio_data_center_tax_break_cost_14_billion_more/', 'https://www.reddit.com/r/Columbus/comments/1tts4au/data_center_protest_wednesday_in_pataskala_east/', 'https://www.reddit.com/r/Ohio/comments/1tj3ygz/data_center_petition/', 'https://www.reddit.com/r/Ohio/comments/1tj696m/how_do_you_does_a_government_tax_data_centers/', 'https://www.reddit.com/r/Ohio/comments/1tlkwpp/vindicated_yes_like_the_dashboard_confessional/', 'https://www.reddit.com/r/Ohio/comments/1t5cwzq/acton_no_more_ai_data_centers/', 'https://www.reddit.com/r/Columbus/comments/1tan4r9/whats_going_on_with_data_centers_and_intel/', 'https://www.reddit.com/r/Ohio/comments/1tu9plq/large_scale_data_center_ban_petition/', 'https://www.reddit.com/r/Ohio/comments/1o3jkei/ohio_tax_break_for_data_centers_could_go_away_if/', 'https://www.reddit.com/r/Ohio/comments/1u6m325/petition_to_ban_hyperscale_data_centers_from_ohio/', 'https://www.reddit.com/r/SeattleWA/comments/1u28bki/were_not_a_company_town_tech_hub_seattle_passes/', 'https://www.reddit.com/r/SeattleWA/comments/1u0o49l/seattle_is_set_to_become_the_biggest_us/', 'https://www.reddit.com/r/Columbus/comments/1pk0cm2/my_aep_electric_bill_is_up_126_while_usage_stays/', 'https://reddit.com/r/Columbus/comments/1rkcw9v/data_center_in_champaign_county_defeated_by', 'https://www.reddit.com/r/Ohio/comments/1skihkc/we_mapped_90_data_center_projects_across_ohio_11/', 'https://reddit.com/r/Ohio/comments/1rfil8k/ohio_towns_are_pushing_back_against_data_centers', 'https://www.reddit.com/r/Columbus/comments/1tpy34h/ohio_pauses_tax_breaks_for_data_centers/', 'https://reddit.com/r/Ohio/comments/1r822la/from_the_ohio_community_on_reddit_ohio_gop_bill', 'https://reddit.com/r/Ohio/comments/1p1pnnf/ashville_opposes_data_center', 'https://www.reddit.com/r/Ohio/comments/1rt8j80/big_tech_unions_ask_ohio_leader_to_leave_data/', 'https://reddit.com/r/Columbus/comments/1m2d23v/aep_puco_now_require_data_centers_to_pay_for_at', 'https://www.reddit.com/r/Ohio/comments/1rvk2x8/report_urges_ohio_lawmakers_to_nix_data_center/', 'https://www.reddit.com/r/Columbus/comments/1rltjl5/city_council_hearing_on_march_11_regarding_the/', 'https://www.reddit.com/r/Ohio/comments/1t40bjd/proposed_amendment_for_data_center_ban_signature/', 'https://www.reddit.com/r/SeattleWA/comments/1txa8ri/data_centers_are_driving_demand_for_gas_from/', 'https://reddit.com/r/Columbus/comments/1qcpudy/i_want_to_petition_against_data_center_water', 'https://www.reddit.com/r/Columbus/comments/1t181h9/oh15_voters_we_need_to_talk_about_adam_miller_don/', 'https://www.reddit.com/r/Ohio/comments/1pcuqj8/amazon_proposes_4b_data_center_in_wilmington/', 'https://www.reddit.com/r/SeattleWA/comments/1twaqla/seattle_or_wa_state_should_do_this_in_first/', 'https://www.reddit.com/r/Ohio/comments/1rp3r8c/ohio_democratic_leader_defends_data_center_tax/', 'https://www.reddit.com/r/Ohio/comments/1tr6hy8/ohio_suspends_data_center_tax_break_as_tech_firms/', 'https://www.reddit.com/r/Columbus/comments/1ston5e/ask_the_experts_data_centers/', 'https://www.reddit.com/r/SeattleWA/comments/1txj24n/data_center_planned_for_downtown_seattle_in_spite/', 'https://www.reddit.com/r/SeattleWA/comments/1t2pten/2_data_center_developers_pull_seattle_plans_amid/', 'https://www.reddit.com/r/Columbus/comments/1s5o5mi/data_center_constitutional_amendment/', 'https://www.reddit.com/r/Ohio/comments/1skug1f/does_anyone_know_amy_actons_position_on_data/', 'https://www.reddit.com/r/Ohio/comments/1u1s9dx/ohio_gop_fckd_every_pretty_good_on_this/', 'https://www.reddit.com/r/Ohio/comments/1s55ak9/is_anyone_else_seeing_how_the_state_is_basically/', 'https://www.reddit.com/r/Ohio/comments/1trensn/data_overload_central_ohio_township_places/', 'https://www.reddit.com/r/Ohio/comments/1tjga4o/ohio_data_center_tax_break_cost_1_billion_more/', 'https://www.reddit.com/r/Columbus/comments/1qcp9s2/the_oh_gop_is_seriously_coming_for_our_wellbeing/', 'https://reddit.com/r/Ohio/comments/1r8dqun/how_amazon_went_about_buying_the_land_for_the', 'https://www.reddit.com/r/Ohio/comments/1stkt4b/data_center_protest_perry_ohio_tonight_530pm/', 'https://www.reddit.com/r/Ohio/comments/1sm1wtc/landsman_pushes_for_federal_regulation_of_data/', 'https://www.reddit.com/r/Columbus/comments/1pdynkd/watchdog_for_electric_grid_in_ohio_other_states/', 'https://www.reddit.com/r/Columbus/comments/1tq4eue/dispatch_headline_gov_mike_dewine_pauses_data/', 'https://www.reddit.com/r/Ohio/comments/1rj6dzx/northeast_ohio_data_center_expansion_project/', 'https://www.reddit.com/r/Columbus/comments/1o31rql/new_50_sales_tax_exemption_for_a_data_center_in/', 'https://www.reddit.com/r/Ohio/comments/1ty49bg/ohio_republican_named_to_lead_data_center/', 'https://www.reddit.com/r/Ohio/comments/1necbtu/ohio_regulators_turn_down_appeal_ok_utilitys_data/', 'https://reddit.com/r/Ohio/comments/1rp2vrj/why_ohio_gave_45m_to_a_data_center_project_that', 'https://www.reddit.com/r/Ohio/comments/1scph5y/hey_since_maine_looks_to_be_banning_new_data/', 'https://www.reddit.com/r/Ohio/comments/1try3v3/ohio_lawmakers_begin_hearings_on_data_centers/', 'https://www.reddit.com/r/Ohio/comments/1ssqi8f/city_of_tiffin_pauses_data_center_development_for/', 'https://www.reddit.com/r/Ohio/comments/1t181u7/oh15_voters_we_need_to_talk_about_adam_miller_don/', 'https://www.reddit.com/r/Ohio/comments/1u1k01u/ohios_biggest_data_centers_secured_decades_of_tax/', 'https://www.reddit.com/r/Columbus/comments/1lkdest/its_time_to_stop_incentivizing_billion_dollar/', 'https://www.reddit.com/r/Ohio/comments/1u1zn5x/kasich_deal_gave_40year_data_center_tax_break_to/', 'https://reddit.com/r/Ohio/comments/1r93l63/the_rush_to_build_ohio_data_centers_tells_us', 'https://reddit.com/r/Ohio/comments/1rvbn9n/submitted_statewide_petition_to_ban_largescale', 'https://www.reddit.com/r/Ohio/comments/1u70uv5/ramaswamy_wants_data_centers_all_over_ohio_and/', 'https://www.reddit.com/r/SeattleWA/comments/1u2by8k/seattle_data_center_ban_heads_to_mayor_wilsons/', 'https://www.reddit.com/r/Columbus/comments/1pf4lyw/aep_ohio_customers_oppose_proposed_electric_rate/', 'https://reddit.com/r/Ohio/comments/1rwasul/rural_ohioans_seek_to_ban_data_centers_through', 'https://www.reddit.com/r/Ohio/comments/1tt2c8g/ohioans_to_fight_against_data_centers_at/', 'https://www.reddit.com/r/Ohio/comments/1ska1xn/secrecy_surrounding_data_center_projects_anger/', 'https://reddit.com/r/Ohio/comments/1r7qujv/ohio_gop_bill_labels_data_center_opposition', 'https://www.reddit.com/r/Ohio/comments/1u03r24/data_centers_are_a_generational_democratic/', 'https://www.reddit.com/r/Ohio/comments/1tgdip4/lawmakers_form_group_to_study_data_centers_in_ohio/', 'https://reddit.com/r/Ohio/comments/1precgr/wilmington_delays_amazon_data_center_approval', 'https://www.reddit.com/r/SeattleWA/comments/1tw8pxo/seattle_advances_ai_data_center_moratorium_bill/', 'https://www.reddit.com/r/Ohio/comments/1s6yi0z/ohio_voters_launch_proposed_amendment_to_keep_big/', 'https://www.reddit.com/r/Ohio/comments/1tqxvs9/ohio_lawmakers_go_deep_on_data_centers/', 'https://reddit.com/r/Ohio/comments/1s4kgi7/push_to_ban_data_centers_in_ohio_takes_step', 'https://www.reddit.com/r/Ohio/comments/1tv0uyw/just_before_moratorium_two_last_ohio_data_centers/', 'https://reddit.com/r/Ohio/comments/1rudv4z/update_on_state_petition_to_ban_largescale_data', 'https://www.reddit.com/r/Ohio/comments/1tdffi2/as_more_ohio_towns_ban_data_centers_lawmakers/', 'https://www.reddit.com/r/Ohio/comments/1ts1r0n/ohio_hits_pause_on_data_center_tax_breaks_after/', 'https://www.reddit.com/r/Columbus/comments/1u21ajk/ohios_biggest_data_centers_secured_decades_of_tax/', 'https://www.reddit.com/r/Ohio/comments/1riyoo4/gop_primary_challenger_eric_watson_slams_ohio_rep/', 'https://www.reddit.com/r/Ohio/comments/1suq5tj/cleveland_councilman_proposes_data_center/', 'https://www.reddit.com/r/SeattleWA/comments/1u0m0gz/tomorrow_6926_2pm_joi

In [ ]:
only_gov_posts = posts[posts["government"] == True].copy()
only_gov_posts.drop(columns=["environment", "infrastructure", "housing", "economy", "life quality", "aesthetics", "technology", "environment sentiment", "environment sentiment degree", "infrastructure sentiment", "infrastructure sentiment degree", "housing sentiment", "housing sentiment degree", "economy sentiment", "economy sentiment degree", "life quality sentiment", "life quality sentiment degree", "aesthetics sentiment", "aesthetics sentiment degree", "technology sentiment", "technology sentiment degree"], inplace=True)
pd.set_option("display.max_colwidth", None)
only_gov_posts.head(30)

           ids  \
3   t3_1febz9m
5   t3_1h8szf0
9   t3_1k7ss6k
11  t3_1lkdest
13  t3_1m1veop
14  t3_1m2d23v
15  t3_1m2pahj
19  t3_1mia19o
24  t3_1mzrm4e
27  t3_1n8diha
29  t3_1necbtu
33  t3_1nqytvq
35  t3_1nw1az0
41  t3_1o31rql
42  t3_1o3jkei
45  t3_1ojcms6
48  t3_1oqts0s
50  t3_1ow2lf2
53  t3_1p1pnnf
57  t3_1pbbwru
58  t3_1pcuqj8
59  t3_1pdynkd
62  t3_1pf4lyw
65  t3_1pk0cm2
66  t3_1pkk14x
67  t3_1plepux
69  t3_1plqgyx
70  t3_1plta23
71  t3_1pm2eg7
76  t3_1precgr

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       text  \
3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Fairfax County board approves new data center regulations, promise further review
5                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Data Centers Approved, Solar Farms Rejected: What Is Going On In Rural Virginia? ("It’s not a choice I’d make – I’d take solar over data centers every time" - Ivy Main)

In [ ]:
# calculating average sentiment based on theme:
# Weigh all posts by their degree in the numerator and denominator, means that the average sentiment will just be +/- 1 if there are only positive or negative themes but other than that does a pretty good job of weighing neutrality
def avg_sentiment_calculation(dataset, theme):
    theme_posts = dataset.loc[dataset[theme] == True]
    if len(theme_posts) > 0:
        pos = theme_posts.loc[theme_posts[f"{theme} sentiment"] == "Positive", f"{theme} sentiment degree"].sum()
        neg = theme_posts.loc[theme_posts[f"{theme} sentiment"] == "Negative", f"{theme} sentiment degree"].sum()
        total = theme_posts[f"{theme} sentiment degree"].sum()
        return (pos-neg)/total
    else:
        return None


print("Number of environmental posts:", len(env_post_ids))
print("Average sentiment of environmental posts:", avg_sentiment_calculation(posts, "environment"))

print("Number of infrastructure-related posts:", len(infr_post_ids))
print("Average sentiment of infrastructural posts:", avg_sentiment_calculation(posts, "infrastructure"))

print("Number of housing-related posts:", len(housing_post_ids))
print("Average sentiment of housing-related posts:", avg_sentiment_calculation(posts, "housing"))

print("Number of economy/jobs-related posts:", len(econ_post_ids))
print("Average sentiment of economy/jobs-related posts:", avg_sentiment_calculation(posts, "economy"))

print("Number of life-quality-related posts:", len(life_qual_post_ids))
print("Average sentiment of life-quality-related posts:", avg_sentiment_calculation(posts, "life quality"))

print("Number of visual-impact-related posts:", len(aesth_post_ids))
print("Average sentiment of visual-impact-related posts:", avg_sentiment_calculation(posts, "aesthetics"))

print("Number of government-related posts:", len(gov_post_ids))
print("Average sentiment of government-related posts:", avg_sentiment_calculation(posts, "government"))

print("Number of technology-related posts:", len(tech_post_ids))
print("Average sentiment of technology-related posts:", avg_sentiment_calculation(posts, "technology"))

Number of environmental posts: 93
Average sentiment of environmental posts: -0.7413206990236969
Number of infrastructure-related posts: 15
Average sentiment of infrastructural posts: -0.6346038645027788
Number of housing-related posts: 5
Average sentiment of housing-related posts: -0.2668288354614979
Number of economy/jobs-related posts: 23
Average sentiment of economy/jobs-related posts: -0.5996791471712967
Number of life-quality-related posts: 18
Average sentiment of life-quality-related posts: -0.8509339116352769
Number of visual-impact-related posts: 7
Average sentiment of visual-impact-related posts: -0.1253349907207954
Number of government-related posts: 234
Average sentiment of government-related posts: -0.1768351420013069
Number of technology-related posts: 232
Average sentiment of technology-related posts: 0.14680419029563618

In [ ]:
posts['year'] = pd.to_datetime(posts['date']).dt.year
year_datasets = {year: posts[posts['year'] == year] for year in range(2010, 2027)}

for theme in theme_cols:
    print(f"Sentiments for {theme}:")
    for date in range(2010, 2027):
        print(f"Amount of posts discussing {theme} in {date}:", len(year_datasets[date].loc[year_datasets[date][theme] == True])) if len(year_datasets[date].loc[year_datasets[date][theme] == True]) > 0 else None
        print(f"Average sentiment for {theme} in {date}:", avg_sentiment_calculation(year_datasets[date], theme)) if len(year_datasets[date].loc[year_datasets[date][theme] == True]) > 0 else None
    print("\n")

Sentiments for environment:
Amount of posts discussing environment in 2025: 14
Average sentiment for environment in 2025: -0.7296912407660786
Amount of posts discussing environment in 2026: 79
Average sentiment for environment in 2026: -0.7433516276769775


Sentiments for infrastructure:
Amount of posts discussing infrastructure in 2025: 6
Average sentiment for infrastructure in 2025: -0.5598690793840242
Amount of posts discussing infrastructure in 2026: 9
Average sentiment for infrastructure in 2026: -0.6779682025761886


Sentiments for housing:
Amount of posts discussing housing in 2024: 1
Average sentiment for housing in 2024: 1.0
Amount of posts discussing housing in 2025: 2
Average sentiment for housing in 2025: -0.4410481251958999
Amount of posts discussing housing in 2026: 2
Average sentiment for housing in 2026: -0.4395968866813848


Sentiments for economy:
Amount of posts discussing economy in 2025: 4
Average sentiment for economy in 2025: -1.0
Amount of posts discussing economy in 2026: 19
Average sentiment for economy in 2026: -0.48063031129904993


Sentiments for life quality:
Amount of posts discussing life quality in 2023: 1
Average sentiment for life quality in 2023: -1.0
Amount of posts discussing life quality in 2025: 1
Average sentiment for life quality in 2025: -1.0
Amount of posts discussing life quality in 2026: 16
Average sentiment for life quality in 2026: -0.8310767590881808


Sentiments for aesthetics:
Amount of posts discussing aesthetics in 2026: 7
Average sentiment for aesthetics in 2026: -0.1253349907207954


Sentiments for government:
Amount of posts discussing government in 2024: 2
Average sentiment for government in 2024: -0.46521951136079487
Amount of posts discussing government in 2025: 28
Average sentiment for government in 2025: -0.23219875892617434
Amount of posts discussing government in 2026: 204
Average sentiment for government in 2026: -0.1657955920983732


Sentiments for technology:
Amount of posts discussing technology in 2022: 2
Average sentiment for technology in 2022: 0.38642775792153544
Amount of posts discussing technology in 2023: 1
Average sentiment for technology in 2023: 0.0
Amount of posts discussing technology in 2024: 3
Average sentiment for technology in 2024: 0.06627284972892934
Amount of posts discussing technology in 2025: 47
Average sentiment for technology in 2025: -0.06865018845848539
Amount of posts discussing technology in 2026: 179
Average sentiment for technology in 2026: 0.20777156449451578